### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by NyesteAmbrusPal** [dalymople/ubxtranslator#1]
Hi,

I want to get all the information of the RELPOSNED data(relPosN,relPosE are the most important ones). How can I do that?
I followed the instructions but nothing happens. Probably I did something wrong but I can't figure out on my own. The code runs down and nothing happens. Please let me know how to solve it. thank you in advance :)

This is my code

import serial

from ubxtranslator import core
from ubxtranslator import predefined

port = serial.Serial('COM8', baudrate=19200, timeout=0.1)

parser = core.Parser([
  predefined.ACK_CLS,
  predefined.NAV_CLS
])
x = parser.register_cls(predefined.NAV_CLS)
cls_name, msg_name, payload = parser.receive_from(port)
print(cls_name, msg_name, payload.lat, payload.lng)
#print(cls_name)
#print(x)

Thank you for your help

**Comment by messplay** [comment]
Hi here "my" working code 
`import serial

from ubxtranslator.core import Parser
from ubxtranslator.predefined import NAV_CLS, ACK_CLS


def run():
    port = serial.Serial("COM53", baudrate=115200, timeout=0.1)

    parser = Parser([
        NAV_CLS, NAV_CLS
    ])

    print("Starting to listen for UBX packets")

    try:
        while True:
            try:
                msg, msg_name, payload = parser.receive_from(port)
                print(msg, msg_name, payload.lat)
            except (ValueError, IOError) as err:
                print(err)

    finally:
        port.close()


if __name__ == '__main__':
    run()
`

**Comment by NyesteAmbrusPal** [comment]
It is not working for me :(

**Comment by messplay** [comment]
Are you activate ubx message?

**Comment by dalymople** [comment]
I'm not convinced that this is an issue with the code, I think that this is an issue with the module configuration. 

I'll close this for now, if you can confirm that you setup UBX messages and they are coming through to the serial port then please reopen this.
