### ISSUE TITLE
UBX-NAV-SAT

### ISSUE THREAD

**Issue by messplay** [dalymople/ubxtranslator#2]
Hi how could I add a UBX-NAV-SAT message, if this frame have a variable lenght in function with sats number

**Comment by dalymople** [comment]
Sorry for the delay! I wasn't subscribed to posts... Let me look into this, at this stage I have not added support for variable length messages, it probably isn't hard to do...

**Comment by dalymople** [comment]
Support for repeated blocks now added and the NAV-SAT message added to the predefined list. This message type should now work.
