### ISSUE TITLE
Messages with variable length

### ISSUE THREAD

**Issue by aal7** [dalymople/ubxtranslator#3]
Hello. None of the predefined messages you've provided are of the type with undetermined length (eg UBX-NAV-DGPS. Could you give any advice on how to form the code for such a message? Many thanks if you can help.

**Comment by n8ur** [comment]
The third byte of the packet (after class and ID) is the payload length.  Maybe implement a message model where the parser returns class, id, and the  len(payload) number of following bytes as a struct that the user can then unpack on their own?

**Comment by jolau** [comment]
this is apparently already implemented (as in #2), but unfortunately the updated version is not shipped over pip. just use the most recent version from this repo.

**Comment by dalymople** [comment]
The latest version is now on pypi and will install via pip.
