### ISSUE TITLE
Message timing

### ISSUE THREAD

**Issue by n8ur** [dalymople/ubxtranslator#4]
Thanks for this module!  It was amazingly easy to get working, except for one simple bit of documentation I'll mention later.

But first, not an issue but a question.  I am using the TIM-TP message to get the quantization error that is to be applied to the next hardware PPS timepulse.  In your stream parsing, you are using "readuntil" which looks for the beginning of the next message.  That means that if you are only outputting one message per second, the read function might not return until the next second, which would make the TIM_TP message outdated.  BUT... it looks like you are using a serial timeout of 0.1 seconds, which should avoid that problem.  Am I correct that's the idea -- the short timeout overrides the readuntil?

Now to the documentation point -- it would be really helpful if your examples would show how to split the message results into separate class, name, and payload variables.  It took me quite a while to figure that out (I was looking for something like "msg.class".  Not a big deal but it would make it easier to get up and running.  Another really minor point is that the the "CustomClass" name you use in the example was a bit confusing.  It would be more helpful if it was named something like "CUSTOM_CLS" to match the message class naming convention.

Thanks again -- I got my test script up and running in less than an hour, compared to farting around almost all day yesterday with another supposed parsing package on github, and still not getting reliable reads.

**Comment by dalymople** [comment]
Hi! Sorry for the delay! And I am glad you found this useful.

On the readUntil method, you are close. It uses readuntil looking for the message prefix bytes. As soon as the the two message prefix bytes are received it will read the rest of the message as quickly as your hardware can get them into the buffer and process immediately.

I'll have a look at the docs and try and make them more clear.

**Comment by dalymople** [comment]
Hi @n8ur, I have just updated the readme to clarify how to split the payload up. do you mind letting me know if that addresses your issue?

**Comment by n8ur** [comment]
Hi @dalymople --

Thanks for the follow-up!  Since it's been a few months, I need to go back to my work files to see if your description matches up with what I found -- in any event, I was able to get proper results in my testing, so the code did work as I needed it to.
