### ISSUE TITLE
Update pip version

### ISSUE THREAD

**Issue by jolau** [dalymople/ubxtranslator#5]
Somehow is the version 0.1.1 distributed over pip not the same as in https://github.com/dalymople/ubxtranslator/commit/810002212bb0037a765197abd8233cfc44b7e200. i.e. the repeated block feature is missing in pip's version. Could you please fix this? :) Such that not everybody has to stumble upon it themself...

**Comment by dalymople** [comment]
Sorry for the delay. I have now updated the pip package to the latest version!
