### ISSUE TITLE
NAV-RELPONSED does not show up even though it is enabled in U-center

### ISSUE THREAD

**Issue by IvanGerov** [dalymople/ubxtranslator#8]
I have a ZED-F9P based set-up that I have deployed on an Ubuntu 18.04 system. I have the RELPOSNED message active and displaying correct rover data in U-center and the config is flashed and stored on an Ardusimple board. When I launch the translator in Ubuntu it displays all active messages, except for RELPOSNED. What could be causing this problem and how could it be possibly solved?

**Comment by dalymople** [comment]
Sorry for the delay here. 
I can duplicate your hardware setup so it is hard to know the issue. If you have access to a debugger I would put a break point in and follow the workings of the parser. You should be able to find the issue from there.
The only obvious issue I could think of would be that the message definition is incorrect and therefore not being parsed correctly.

**Comment by dalymople** [comment]
Hmm, I just double checked the code. The packet definition matches the data sheet and all parsing errors should throw exceptions. 
I don't think this is an error with the code. I think the packet may not be being transmitted?
To replicate this error I really need a copy of the serial byte stream making it to the device. This would let me add it to the tests.
I'm going to close this issue for now pending further info.
